meta_title: "Budd-fit challenge"
meta_description: "An app that helps you reach your best version, while having fun with your friends"
meta_image: "budd-fit-cover.png" # should exist in `app/assets/images/`
